inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - spec/spec_helper.rb
    - spec/rails_helper.rb
  TargetRubyVersion: 2.6.3

Rails/OutputSafety:
  Enabled: false
