version: 1
update_configs:
  - package_manager: ruby:bundler
    directory: /
    update_schedule: daily
    allowed_updates:
      - match:
          update_type: security
      - match:
          dependency_name: gds-api-adapters
      - match:
          dependency_name: govuk_publishing_components
      - match:
          dependency_name: rubocop-govuk
